name: Icecat build script
on: workflow_dispatch

jobs:
  build-script:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get release version
        run: echo "version=$(bash check-updates.sh --version-only | awk '{print $1}')" >> $GITHUB_ENV

      - name: Install build dependencies
        run: /bin/sh build.sh install_deps

      - name: Run ./makeicecat
        run: /bin/sh build.sh make_icecat

      - name: Build the Icecat program
        run: /bin/sh build.sh build_icecat

      - name: Prepare files for Debian package
        run: /bin/sh build.sh prepare_deb

      - name: Update the changelog
        run: /bin/sh build.sh update_changelog

      - name: Build the .deb package
        run: /bin/sh build.sh build_deb

      - name: Release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: ${{ steps.version.outputs.version }}
          tag_name: ${{ github.ref }}
          body: "New Icecat release: ${{ env.version }}"
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Upload .deb package artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./icecat-${{ env.version }}-1_amd64.deb
          asset_name: icecat-${{ env.version }}-1_amd64.deb
          asset_content_type: application/vnd.debian.binary-package
